sudo: required

services:
    - docker

language: r

r:
    - 3.6.3

branches:
  only:
    - main

cache:
  packages: true
  directories:
    - $HOME/bin

before_install:
    - "docker pull rocker/verse:3.6.3"
    - sudo apt-get --yes --force-yes update -qq

# do not install any R packages
    # r_packages:
#     - bookdown
